name: Workflow trigged by dispatch

on: 
  workflow_dispatch:
    inputs:
      topic:
        description: 'Topic'     
        required: true
        default: 'UnSorted'
      title:
        description: 'Bookmark Title'
        required: true
      url:
        description: 'Bookmark URL'
        required: true
        default: 'https://dev.null'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Create url file"
        run: |
          topic=${{ github.event.inputs.topic }}
          title="${{ github.event.inputs.title }}"
          url="${{ github.event.inputs.url }}"
          echo "Topic: ${topic}"
          echo "Title ${title}"
          echo "URL: ${url}"
          mkdir -p $topic
          fname=$(echo "${title}.url.md" | tr "[:upper:]" "[:lower:]" | tr -s ' ' | tr ' ' '_')
          echo "[${title}](${url})" > ${topic}/$fname
          ls -l ${{ github.event.inputs.topic }}
          git diff
          git config --global user.email "readme-bot@github.bot"
          git config --global user.name "README-bot"
          git add ${topic}/$fname && git commit -m "Add Bookmark from Slack"
          git push
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update README
        run: |-
          python update_readme.py --rewrite
          cat README.md
      - name: Commit and push if README changed
        run: |-
          git diff
          git config --global user.email "readme-bot@github.bot"
          git config --global user.name "README-bot"
          git diff --quiet || (git add README.md && git commit -m "Updated README")
          git push
