name: Workflow trigged by dispatch

on: 
  workflow_dispatch:
    inputs:
      topic:
        description: 'Topic'     
        required: true
        default: 'UnSorted'
      title:
        description: 'Bookmark Title'
        required: true
      url:
        description: 'Bookmark URL'
        required: true
        default: 'https://dev.null'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Topic: ${{ github.event.inputs.topic }}"
        echo "Title" ${{ github.event.inputs.title }}"
        echo "URL: ${{ github.event.inputs.url }}"
        mkdir -p ${{ github.event.inputs.topic }}"
        fname=$(echo "${{ github.events.inputs.title }}.md" | tr "[:upper:]" "[:lower:]" | tr -s ' ' | tr ' ' '_')
        echo "[${{ github.events.inputs.title }}](${{ github.events.inputs.url }})" > ${{ github.event.inputs.topic }}/$fname
        ls -l ${{ github.event.inputs.topic }}
