name: Workflow trigged by dispatch

on: 
  workflow_dispatch:
    inputs:
      topic:
        description: 'Topic'     
        required: true
        default: 'UnSorted'
      title:
        description: 'Bookmark Title'
        required: true
      url:
        description: 'Bookmark URL'
        required: true
        default: 'https://dev.null'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        topic=${{ github.event.inputs.topic }}
        title="${{ github.event.inputs.title }}"
        url="${{ github.event.inputs.url }}"
        echo "Topic: ${topic}"
        echo "Title ${title}"
        echo "URL: ${url}"
        mkdir -p $topic"
        fname=$(echo "${title}.md" | tr "[:upper:]" "[:lower:]" | tr -s ' ' | tr ' ' '_')
        echo "[${title}](${url})" > ${topic}/$fname
        ls -l ${{ github.event.inputs.topic }}
